###
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer 

{
    "title": "reuben sandwiches are pretty dang tasty yo",
    "author": "the cheesemaster",
    "url": "reubensandwiches.com",
    "likes": 83
}

###
DELETE http://localhost:3003/api/blogs/690a113b0b17f8bcc0a0a779
content-type: application/json
Authorization: Bearer 