###
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "salad",
    "author": "lettuce mctomato",
    "url": "salad.com",
    "likes": 63748
}