###
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY5MDljMzMzOGYxZjgyZTlmMDVhZjVkNyIsImlhdCI6MTc2MjQxODk2NCwiZXhwIjoxNzYyNDIyNTY0fQ.5cqw06bgega21GbR_n2VMsLbWwW_yJY88rae3sfSIYY

{
    "title": "test blog number 2",
    "author": "test mctest",
    "url": "test2.com",
    "likes": 83
}

###
DELETE http://localhost:3003/api/blogs/690b4ceec7995ac318d81b08
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY5MDljMzMzOGYxZjgyZTlmMDVhZjVkNyIsImlhdCI6MTc2MjM0ODI5MCwiZXhwIjoxNzYyMzUxODkwfQ.6dK-HNx7134lE8Su7A2mAd-OvMWp14B8LlTcsnYgi0A

###
PUT http://localhost:3003/api/blogs/690ca4cde1647bfc385ff052
content-type: application/json

{
    "title": "eggs",
    "author": "eggs",
    "url": "eggs",
    "likes": 748,
    "user": "6909c04f622842b9c6122167"
}

###
POST http://localhost:3003/api/blogs/69235cc0353d703066b49f81/comments
content-type: application/json

{
    "content": "bros"
}